# Configuration de base du site
title: Mon Site Jekyll
description: Un site web construit avec Jekyll et hébergé sur GitHub Pages
baseurl: ""
url: "https://finankox.github.io" 
# Configuration des pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      Title: "index"
      permalink: /

# Configuration pour la page 'about'
  - scope:
      path: "about.html"
      type: "pages"
    values:
      layout: "page"
      title: "about"
      permalink: /about

  - scope:
      path: "search.html"
      type: "pages"
    values:
      layout: "page"
      title: "search"
      permalink: /search

# Configuration pour les redirections
  - scope:
      path: "indeed.html"
    values:
      layout: ""
      permalink: /searching/